version: "3.9"

networks:
  chargeflow-network:
    external: true

services:
  charge-manager:
    image: 192.168.56.10:5000/charge-manager:latest
    environment:
      SERVER_PORT: 8081

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chargerdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      PROXY_SOAP_URL: http://charge-proxy:8080/ws

      # Email Configuration (from .env)
      MAIL_HOST: ${MAIL_HOST:-smtp.example.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: luiz-nascimento.ln@academico.ifpb.edu.br
      MAIL_PASSWORD: etbr ehxz urfd qecj
      MAIL_ENABLED: ${MAIL_ENABLED:-true}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
    ports:
      - "8081:8081"
    networks:
      - chargeflow-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
