version: "3.9"

networks:
  chargeflow-network:
    external: true

services:
  charge-proxy:
    image: 192.168.56.10:5000/charge-proxy:latest
    environment:
      SERVER_PORT: 8080

      MANAGER_SOAP_URL: http://charge-manager:8081/ws

      ASAAS_BASE_URL: https://sandbox.asaas.com/api/v3
      ASAAS_API_KEY: $$aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmQ2ZDVkMzE4LWY0Y2QtNDk5MC04NTU5LTExYjc2N2NhODFjZTo6JGFhY2hfMjZhZDRlYTgtNmEyZi00NzY1LWI3N2UtMzkwNDU4YThkZmJh
      ASAAS_WEBHOOK_TOKEN: your_webhook_token_here
    ports:
      - "8080:8080"
    networks:
      - chargeflow-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
