spring.application.name=charge-proxy

server.port=8080

logging.level.root=INFO

asaas.base-url=${ASAAS_BASE_URL:https://sandbox.asaas.com/api/v3}
asaas.api-key=${ASAAS_API_KEY:dummy}
asaas.webhook.token=${ASAAS_WEBHOOK_TOKEN:dummy}

manager.soap.url=${MANAGER_SOAP_URL:http://charge-manager/ws/charge-manager.wsdl}