CREATE TABLE charge_details (
    id SERIAL PRIMARY KEY,
    charge_id INTEGER UNIQUE NOT NULL REFERENCES charge(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    payload JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
